### ISSUE TITLE
golangci-lint error in cimg-go:1.19

### ISSUE THREAD

**Issue by s4s7** [CircleCI-Public/cimg-go#189]
## Meta:
Operating System: OSX Monterey 12.0.1, Intel chip

## Current behavior:
I can't run golangci-lint with cimg/go:1.19.0.

```
docker run -it cimg/go:1.19.0

circleci@61aaede53bc0:~/project$ golangci-lint version
panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt

goroutine 1 [running]:
github.com/go-critic/go-critic/checkers.init.22()
	github.com/go-critic/go-critic@v0.6.3/checkers/embedded_rules.go:47 +0x4b4
```

**Comment by stlava** [comment]
+1 `golangci-lint` needs to be updated to `1.48.0`

**Comment by felicianotech** [comment]
Is this due to a compatibility issue between golangci-lint and Go v1.19?
